### ISSUE TITLE
Sync script is failing / not currently running

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/eclipsefdn-github-sync#110]
I took a look at the logs after deploying our latest update and I can see the following error message in the logs:

```
Error: Cannot find module './teams/StaticTeamManager.js'
Require stack:
- /app/src/Sync.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/app/src/Sync.js:68:45)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/app/src/Sync.js' ]
}
```

**Comment by autumnfound** [comment]
This fix is live and the script is currently running
